### ISSUE TITLE
There's an issue

### ISSUE THREAD

**Issue by AverageAlien** [TundrumMax/Chat-2.0#2]
After suddenly disappearing from one say to another I feel like I needed to address this, get it off from my chest.
I cant believe I was once the single most active member on this server and in a matter or minutes I went all the way down to muting the server altogether. This community has gotten so unimaginably toxic that even I, arguably one of the heaviest shitposters on the entire server, have decided to leave this cancerous, toxic place. From the horrible and unwelcoming people to the incapability of most moderators, this place has proven to be everything but a half decent server. Now all I do here is do my daily gag greeting and leave it unread until next day or until someone decides to mention me for god knows what reason. I pity all the people that have to stand these horrible conditions on a daily basis.
With this said I would like to give a huge thanks to all the people who have seemingly tried to support me in this place. I appreciate everything you have done for me. I'm not saying I'm leaving this atrocious place, but rather trying to start anew. I hope this doesn't get sunk in the sea of toxicity that's about to come.

Please consider what I just said

**Comment by TundrumMax** [comment]
bruh

**Comment by AverageAlien** [comment]
yep
